version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm i -g prisma
      - run: prisma deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
